Release/v1.0.0
shoplineapp/app-bridge-js pull request #1
Opened 2022-03-03 11:00 UTC by yfleung3

2022-03-08 03:34 UTC, rayway30419 commented on dist/features/get-session-token/app-bridge-feature.js
> +export var getSessionToken = {
decoded token要不要存一份property 每次decoding有點重複

2022-03-08 03:49 UTC, rayway30419 requested changes
Should we store a token object with decoded payload?

2022-03-09 09:48 UTC, Seitk approved these changes

2022-03-09 10:38 UTC, lamkaka approved these changes

2022-04-26 08:08 UTC, merged